# Generated by Django 6.0.5 on 2026-05-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_course_created_at_remove_course_pptx_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='like_count',
        ),
    ]
