# Generated by Django 6.0.5 on 2026-05-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_trainer_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='twitter',
        ),
    ]
