# Generated by Django 6.0.5 on 2026-06-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
